// src/shared/components/jsx/ViewsCounter.tsx
import { useEffect } from 'react';

import { useViews } from '~/shared/hooks';

interface ViewsCounterProps {
	slug: string;
}

export function ViewsCounter({ slug }: ViewsCounterProps) {
	const { views, isLoading, isError } = useViews(slug);

	useEffect(() => {
		const registerView = () => fetch(`/api/views/${slug}.json`, { method: 'POST' });

		registerView();
	}, [slug]);

	if (isLoading || isError) return <small className="text-sm">--</small>;

	return <span className="text-sm">{`${views} views` ?? '--'}</span>;
}

// src/shared/components/svelte/ViewsCounter.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { BASE_URL } from '~/shared/constants';

	let views = 0;
	export let slug = '';

	onMount(async () => {
		const res = await fetch(`${BASE_URL}/api/views/${slug}.json`, {
			method: 'POST',
		});
		const data: { total: number } = await res.json();

		views = data.total;
	});
</script>

<span class="text-sm">{`${views} views` ?? '--'}</span>
