// src/shared/components/svelte/TopTracks.svelte
<script lang="ts">
	import clsx from 'clsx';
	import { useSWR } from 'sswr';

	import type { TopSpotifyTracks, Track } from 'lib/spotify';

	const { data } = useSWR<TopSpotifyTracks>('/api/spotify/top-tracks.json');
</script>

{#if !$data?.tracks}
	<p class="mt-8 text-center opacity-70">No data available...</p>
{:else}
	<ul class="mt-4 md:columns-2 gap-x-10">
		{#each $data?.tracks as track, idx (track.id)}
			<li class={clsx('flex items-center justify-between border-b border-surface-four')}>
				<div class="first-of-type:flex first-of-type:items-baseline">
					<span class="text-sm font-medium text-font-two opacity-70">{idx + 1}</span>
					<div class="flex flex-col p-5 pl-3">
						<a
							href={track.songUrl}
							class={clsx(
								'overflow-hidden overflow-ellipsis whitespace-pre-wrap hover:underline',
								'underline-offset-2 hover:text-brand decoration-wavy'
							)}
							target="_blank"
							rel="noopener noreferrer"
						>
							{track.title}
						</a>
						<small class="overflow-hidden whitespace-pre-wrap opacity-70 overflow-ellipsis">
							{track.artists}
						</small>
					</div>
				</div>
				<div>
					<img src={track.images[0].url} width={40} height={40} alt={track.title} />
				</div>
			</li>
		{/each}
	</ul>
{/if}

// src/shared/components/jsx/TopTracks.tsx
import useSWR from 'swr';
import clsx from 'clsx';

import { fetcher } from 'lib/fetcher';
import type { TopSpotifyTracks, Track } from 'lib/spotify';

export function TopTracks() {
	const { data } = useSWR<TopSpotifyTracks>('/api/top-tracks', fetcher);

	if (!data?.tracks) return <p className="mt-8 text-center opacity-70">No data available...</p>;

	return (
		<ul className="mt-4 md:columns-2 gap-x-10">
			{data?.tracks.map((track: Track, idx: number) => {
				const { id, artists, songUrl, title, images } = track;

				return (
					<li
						key={id}
						className={clsx('flex items-center justify-between border-b border-surface-four')}
					>
						<div className="first-of-type:flex first-of-type:items-baseline">
							<span className="text-sm font-medium text-font-two opacity-70">{idx + 1}</span>
							<div className="flex flex-col p-5 pl-3">
								<a
									href={songUrl}
									className={clsx(
										'overflow-hidden overflow-ellipsis whitespace-pre-wrap hover:underline',
										'underline-offset-2 hover:text-brand decoration-wavy'
									)}
									target="_blank"
									rel="noopener noreferrer"
								>
									{title}
								</a>
								<small className="overflow-hidden whitespace-pre-wrap opacity-70 overflow-ellipsis">
									{artists}
								</small>
							</div>
						</div>
						<div>
							<img src={images[0].url} width={40} height={40} />
						</div>
					</li>
				);
			})}
		</ul>
	);
}
