// src/shared/components/svelte/ViewsCounter.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { BASE_URL } from '~/shared/constants';

	let views = 0;
	export let slug = '';

	onMount(async () => {
		const res = await fetch(`${BASE_URL}/api/views/${slug}.json`, {
			method: 'POST',
		});
		const data: { total: number } = await res.json();

		views = data.total;
	});
</script>

<span>{`${views} views` ?? '--'}</span>

// src/components/vue/ViewsCounter.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue';

const count = ref(0);
const { views, slug } = defineProps<{
    views: number;
    slug: string;
}>();

onMounted(async () => {
    const res = await fetch('/api/views/' + slug + '.json', {
        method: 'POST'
    });
    const data: { views: number } = await res.json();
    count.value = data.views;
});
</script>

<template>
    <span>{{ count ?? views }} views</span>
</template>
