// src/components/svelte/ViewsCounter.svelte
<script lang="ts">
    import { onMount } from 'svelte'

    let count: number
    export let views: number
    export let slug: string

    onMount(async () => {
        const response = await fetch('/api/views/' + slug + '.json', {
            method: 'POST'
        })
        const data: { views: number } = await response.json()
        count = data.views
    })
</script>

<span>{count ?? views} views</span>

// src/components/vue/ViewsCounter.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue';

const count = ref(0);
const { views, slug } = defineProps<{
    views: number;
    slug: string;
}>();

onMounted(async () => {
    const res = await fetch('/api/views/' + slug + '.json', {
        method: 'POST'
    });
    const data: { views: number } = await res.json();
    count.value = data.views;
});
</script>

<template>
    <span>{{ count ?? views }} views</span>
</template>
